# ****************
# USERS (Usuários)
# ****************
### Cria usuário VENDEDOR
POST http://localhost:3333/users HTTP/1.1
content-type: application/json

{
    "name": "Sicrano Vendedor Sale",
    "email": "sicrano.sale@email.com",
    "password": "123abc"
}

### Cria usuário CLIENTE
POST http://localhost:3333/users HTTP/1.1
content-type: application/json

{
    "name": "Fulano Cliente Customer",
    "email": "fulano.customer@email.com",
    "password": "123abc"
}

### # # # # # # # # # # # # # # # # # #
GET http://localhost:3333/users HTTP/1.1
content-type: application/json